[package]
name = "memayu-config"
version.workspace = true
edition.workspace = true
description = "Memayu config/env loading & validation"

[dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"] }
dirs = "6"
toml = "0.8"
memayu-core = { path = "../memayu-core" }

[dev-dependencies]
indoc = "2"
